version: '3.0'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
    container_name: ${PROJECT_NAME}-nginx
    ports:
      - "80:80"
    links:
      - app
      - nuxt
  nuxt:
    build:
      context: ./front
      args:
        - MAIN_DOMAIN=${NUXT_MAIN_DOMAIN}
    expose:
      - "3000"
    container_name: ${PROJECT_NAME}-nuxt
  app:
    build:
      context: .
    container_name: ${PROJECT_NAME}-back
    restart: always
    links:
      - mysql:mysql
    environment:
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: ${PROJECT_NAME}-pma
    links:
      - mysql:mysql
    ports:
      - "8003:80"
    environment:
      - "PMA_HOST=mysql"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql
    container_name: ${PROJECT_NAME}-mysql
    environment:
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
volumes:
  mysql:
